# -*- coding: utf-8 -*-
"""McDougall.Robyn-PythonCode-ITT103-F2023.py.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ugopWmIEoybLbC0Ssm56Fu_q6wWD-ncN
"""

#Author:Robyn McDougall
#- Date Created: December 11, 2023
#- Course: ITT103
#- Purpose: This code was created to be a reservation system for a luxury bus line.

# declaring variables
first_class_seats, business_class_seats, economy_seats = 27, 38, 56

# array of bus types
bus_category = ['First Class', 'Business Class','Economy Class']



all_seats = 0
seats_reserved = 0
num_reserved = 0
bus_type = ""


# Declaring seat arrays
fc_seats = [[0] * 3 for _ in range(9)]
bc_seats = [[0] * 4 for _ in range(10)]
ec_seats = [[0] * 4 for _ in range(14)]


# Defining a function to display menu
def menu():
  print("Welcome to UCC Signature Express Limited where your safety and time are our priorities!")
  print()   # added these to print white spaces so that each line is separated
  print("Our reservation options are: First Class, Business Class and Economy")
  print()


  while True:
    reservation = input("Please select your reservation type: f for First Class, b for Business Class, e for Economy, or q for quit: ")
    print()

# created an elif statement to loop through the different reservation options given
    if reservation.lower() == 'f':
      all_seats = first_class_seats
      global  bus_type
      bus_type = "First Class"
      row_num = int(input("Please select row number between 1 and 9: "))
      print()
      if 0 < row_num <= 9:
        seats_col = int(input("Please select 1 for window seat, 2 for aisle seat or 3 to cancel: "))
        print()
        reserved(row_num, seats_col, fc_seats, bus_type)
        break
        print()
      else:
        print("Invalid row number. Please choose between 1 and 9.")
        continue
        print()


    elif reservation.lower() == 'b':
      all_seats = business_class_seats
      bus_type = "Business Class"
      row_num = int(input("Please select row number between 1 and 10: "))
      print()
      if 0 < row_num <= 10:
        seats_col = int(input("Please select 1 for window seat, 2 for aisle seat or 3 to cancel: "))
        reserved(row_num, seats_col, bc_seats, bus_type)
        break
        print()
      else:
        print("Invalid row number. Please choose between 1 and 10")
        continue
        print()

    elif reservation.lower() == 'e':
      all_seats = economy_seats
      bus_type = "Economy"
      print()
      row_num = int(input("Please select row number between 1 and 14: "))

      print()
      if 0 < row_num <= 14:
        seats_col = int(input("Please select 1 for window seat, 2 for aisle seat or 3 to cancel: "))
        print()
        reserved(row_num, seats_col, ec_seats, bus_type)
        break
        print()
      else:
        print("Invalid row number. Please choose between 1 and 14")
        continue
        print()

    elif reservation.lower() == 'q':
      print("Reservation Type: ", bus_category[0] )
      print("Number of seats: ",first_class_seats)
      print("Total number of seats reserved:", num_seats_reserved(fc_seats))

      print()
      print("Reservation Type: ", bus_category[1])
      print("Number of seats: ",business_class_seats)
      print("Total number of seats reserved:", num_seats_reserved(bc_seats))

      print()
      print("Reservation Type: ", bus_category[2])
      print("Number of seats: ",economy_seats)
      print("Total number of seats reserved: ", num_seats_reserved(ec_seats))
      break

    else:
      print("Invalid choice!")
      print()

      continue


# defining a function to reserve a seat
def reserved(row_num,  seats_col, seat_data, bus_class):
    global seats_reserved
    global bus_type # global to allow the variable to be changed while in a function
    global fc_seats
    global bc_seats
    global ec_seats

    if seats_col == 1:

        if bus_class == 'First Class':
          if fc_seats[row_num-1][0] == 0:
              fc_seats [row_num-1][0] = 1
              print("You have selected: ", bus_class)
          else:
            print("This seat is already reserved")

        if bus_class == 'Business Class':
          if bc_seats [row_num-1][0] == 0:
             bc_seats [row_num-1][0] = 1
             print("You have selected: ", bus_class)
          else:
            print("This seat is already reserved")

        if bus_class == 'Economy':
          if ec_seats [row_num-1][0] == 0:
             ec_seats [row_num-1][0] = 1
             print("You have selected: ", bus_class)
          else:
            print("This seat is already reserved")



    elif seats_col == 2:
        if bus_class == 'First Class':
          if fc_seats[row_num-1][1] == 0:#     the second col, if it is empty,
              fc_seats [row_num-1][1] = 1   # assign 1
              print("You have selected: ", bus_class)
          else:
            print("This seat is already reserved")


        if bus_class == 'Business Class':
          if bc_seats[row_num-1][1] == 0:
              bc_seats [row_num-1][1] = 1
              print("You have selected: ", bus_class)
          else:
            print("This seat is already reserved")


        if bus_class == 'Economy':
          if ec_seats[row_num-1][1] == 0:
              ec_seats [row_num-1][1] = 1
              print("You have selected: ", bus_class)
          else:
            print("This seat is already reserved")


    elif seat_data == 3:
        print("Your reservation has been cancelled. We hope to serve you soon.")
    else:
        print("Invalid seat type selected!")

def num_seats_reserved(seats_array):
  global num_reserved
  num_reserved = 0
  for record in seats_array:
    for item in record:
      if item == 1:
        num_reserved += 1

       # these were added here to visualize the arrays during the reservation process; troubleshooting
      # print("First Class ", fc_seats)
      # print("business Class ",bc_seats)
      # print("economy Class ",ec_seats)

      return num_reserved


while True:
  menu()
  if input("Would you like to make another reservation? (Y/N): ").upper() != 'Y':
    print()
    print("Thank you for choosing UCC Express. Please come again soon.")
    break